# Generated by Django 3.2.5 on 2021-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_key',
            field=models.TextField(null=True),
        ),
    ]
