# Generated by Django 3.2.5 on 2021-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stream_key',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
