# Generated by Django 3.2.5 on 2021-07-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_stream_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_key',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
