# Generated by Django 3.2.5 on 2021-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_watch_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_name',
            field=models.TextField(default='Stream Name'),
        ),
    ]
